# serviceaccounts.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-deployer
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
  namespace: testing
