---
# Namespace for sample application
apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    istio-injection: enabled

---
# Simple HTTP echo service - Version 1
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: sample-app
  labels:
    app: echo
    service: echo
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 5678
  selector:
    app: echo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v1
  namespace: sample-app
  labels:
    app: echo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
      version: v1
  template:
    metadata:
      labels:
        app: echo
        version: v1
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from Istio Echo v1"
            - "-listen=:5678"
          ports:
            - containerPort: 5678
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
# Simple HTTP echo service - Version 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v2
  namespace: sample-app
  labels:
    app: echo
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      version: v2
  template:
    metadata:
      labels:
        app: echo
        version: v2
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from Istio Echo v2"
            - "-listen=:5678"
          ports:
            - containerPort: 5678
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
# Client pod for testing
apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: sample-app
  labels:
    app: curl-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi

---
# ServiceAccount for echo service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo
  namespace: sample-app
